draw/urls.py
from django.urls import path

from . import views

app_name = 'draw'
urlpatterns = [
    path('', views.index, name='index'),
    path('card/', views.card_new, name='card_new'),
    # path('card/<int:pk>/', views.card_detail, name='card_detail'),
    path('card/detail/', views.card_detail, name='card_detail'),

]

drawacard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('draw/', include('draw.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('card/', views.card_new, name='card_new'),
    path('card/<int:pk>/', views.card_detail, name='card_detail'),
    # path('card/detail/<int:card_id>', views.card_detail, name='card_detail'),

]

home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Card(models.Model):

    LANG_CHOICES = [
        ('ko', 'Korean'),
        ('ja', 'Japanese'),
        ('zhs', 'Chinese'),
    ]

    # card = models.ForeignKey(Card, on_delete=models.CASCADE)

    language = models.CharField(
        max_length=10,
        choices=LANG_CHOICES,
        default='ko',
    )

    keyword = models.CharField(max_length=200,null=True,blank=True)
    drawn_date = models.DateTimeField(blank=True, null=True)

    card_name = models.CharField(max_length=200,null=True,blank=True)
    card_text = models.TextField(null=True,blank=True)

    def __str__(self):
        if self.card_name:
            return self.card_name + " / " +self.language
        else:
            return self.language
        # if self.language:
        #     return "Language: " + self.language + " / Keyword: "+ self.keyword
        # return "Language: " + self.language

    def drawn(self):
        self.drawn_date = timezone.now()
        self.save()

home/forms.py
from django import forms

from .models import Card

class CardForm(forms.ModelForm):

    class Meta:
        model = Card
        fields = ('language', 'keyword',)

home/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Card

from .forms import CardForm
from django.utils import timezone

# for json data
import requests, json, random

def index(request):
    # return HttpResponse("Hello, world. You're at the draw index.")
    all_card = Card.objects.all()
    context = {'all_card': all_card}
    return render(request, 'home/index.html', context)


def card_new(request):

    if request.method == "POST":
        form = CardForm(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.author = request.user
            card.drawn_date = timezone.now()

            # card.save()

            # save the input as chosen_variables
            chosen_language = card.language

            # implement the language variant
            if chosen_language == 'ko':
                language = 'Korean'
            elif chosen_language == 'ja':
                language = 'Japanese'
            else:
                language = 'Chinese'

            # if there is a keyword
            if not card.keyword == None:
                response_string = 'https://api.scryfall.com/cards/search?q=lang%3A'
                response_string += chosen_language

                chosen_keyword = card.keyword
                response_string += '+' + chosen_keyword

                response = requests.get(response_string)
                randomcard = response.json()

                if randomcard["object"] == 'error':
                    return render(request, 'home/card_404.html')

                total_cards = int(randomcard["total_cards"])
                random_card_index = random.randint(0,total_cards-1)
                result = randomcard["data"][random_card_index]


            else:
                response_string = 'https://api.scryfall.com/cards/random?q=lang%3A'
                response_string += chosen_language

                response = requests.get(response_string)
                result = response.json()


            try:
                printed_name = result['printed_name']
            except:
                result['printed_name'] = ""
            try:
                printed_text = result['printed_text']
            except:
                result['printed_text'] = ""
            try:
                oracle_text = result['oracle_text']
            except:
                result['oracle_text'] = ""
            try:
                printed_type_line = result['printed_type_line']
            except:
                result['printed_type_line'] = ""

            card.card_name = result['name']
            card.card_text = result['oracle_text']

            card.save()

            name = result['name']
            printed_name = result['printed_name']

            type_line = result['type_line']
            printed_type_line = result['printed_type_line']

            oracle_text = result['oracle_text']
            printed_text = result['printed_text']

            context = {
                'name': name,
                'printed_name':printed_name,
                'type_line':type_line,
                'printed_type_line':printed_type_line,
                'oracle_text':oracle_text,
                'printed_text':printed_text,
                'language':language
                }

            return render(request, 'home/card_detail.html', context)
    else:
        form = CardForm()
    return render(request, 'home/card_new.html', {'form': form})

def card_detail(request, card_id):

    # card_drawn = get_object_or_404(Card, pk=card_id)
    # try:
    #     card_drawn = Card.objects.filter(pk=request.POST['this needs to be input name'])
        # card.choice_set.get(pk=request.POST['choice'])
    #     pass
    # should I put something here? so that it processes something?
    return render(request, 'home/card_detail.html', {'card_drawn': card_drawn})

# def vote(request, question_id):
#     # return HttpResponse("You're voting on question %s." % question_id)
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <title>
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'home/css/backgroundTransition.min.css' %}" />

    </head>

    <body class="{% block body_class %}{% endblock %}">
      <!-- <div class="backgroundTransition"> -->
        <main class="container backgroundTransition">

          <!-- <img class="background active" src="{% static "home/img/bg_00.jpg" %}" id="bg0" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_01.jpg" %}" id="bg1" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_02.jpg" %}" id="bg2" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_03.jpg" %}" id="bg3" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_04.jpg" %}" id="bg4" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_05.jpg" %}" id="bg5" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_06.jpg" %}" id="bg6" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_07.jpg" %}" id="bg7" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_08.jpg" %}" id="bg8" alt="background"/>
          <img class="background inactive" src="{% static "home/img/bg_09.jpg" %}" id="bg9" alt="background"/> -->
          <!-- <img class="background" src="{% static "home/img/bg_00.jpg" %}" id="bg" alt="background"/> -->
          <!-- <img class="background" src="https://img00.deviantart.net/8e77/i/2015/143/9/e/tasipurr_the_golden_paw_by_alradeck-d8ufbfx.jpg" id="bg" alt="background"/>
          <img class="background" src="https://img00.deviantart.net/bce0/i/2015/205/5/b/deathrite_salmon_by_alradeck-d92mqeo.jpg" id="bg" alt="background"/> -->
          <!-- <img class="background" src="{% static "home/img/bg_01.jpg" %}" id="bg" alt="background"/> -->

        {% block content %}

        {% endblock %}
      </main>
      <!-- </div> -->
    </body>

    {# Global javascript #}


    <!-- <script type="text/javascript" src="backgroundTransition.js"></script> -->
    <script type="text/javascript" src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/jquery.flip.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/backgroundTransition.js' %}"></script>
    <script type="text/javascript" src="{% static 'home/js/drawacard.js' %}"></script>

</html>

home/templates/home/card_404.html
{% extends "home/base.html" %}

{% load static %}

{% block body_class %}card-detail{% endblock %}

{% block content %}

<div class="flexbox">
  <div class="card--button show-english" style="visibility:hidden;">
    <span class="text--white text--large font--beleren">
      <a href="#" class="show--english">Show in English</a>
      <a href="#" class="show--otherlang hide">Show in {{language}}</a>
    </span>
  </div>

  <div id="card">

    <div class="card--container view--text front">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black font--mtgx english">
          <span class="card-name"><b>Unfortunate End</b></span>
          <!-- <span class="card-type">{{ printed_type_line }}</span> -->
          There is no such card.
        </p>
      </div>
    </div>

    <div class="card--container view--text back">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black font--mtgx english">
          <span class="card-name"><b>Unfortunate End</b></span>
          <!-- <span class="card-type">{{ type_line }}</span> -->
          There is no such card.
        </p>
        <div class="share--card font--mtgx">
          <span class="card-share">Share This Card</span>
          <input class="share-input" type='text' value="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}"></input>
        </div>
      </div>
    </div>

  </div>

  <div class="card--button draw-again">
    <span class="text--white text--large font--beleren"><a href="{% url 'home:card_new' %}">Draw Another Card</a></span>
  </div>
</div>
{% endblock %}

<script type="text/javascript" src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/drawacard.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/jquery.flip.min.js' %}"></script>

<script>
$(".card-share").click(function() {
  console.log("blueberries are wonderful.");
  $(".share-input").toggleClass('active');
});
</script>

home/templates/home/card_detail.html
{% extends "home/base.html" %}

{% load static %}

{% block body_class %}card-detail{% endblock %}

{% block content %}

<div class="flexbox">
  <div class="card--button show-english">
    <span class="text--white text--large font--beleren">
      <a href="#" class="show--english">Show in English</a>
      <a href="#" class="show--otherlang hide">Show in {{language}}</a>
    </span>
  </div>

  <div id="card">

    <div class="card--container view--text front">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black korean">
          <span class="card-name"><b>{{ printed_name }}{{ card_drawn }}</b></span>
          <span class="card-type">{{ printed_type_line }}</span>
          {{ printed_text }}
        </p>
        <!-- <div class="share--card font--mtgx">
          <span class="card-share">Share This Card</span>
          <input class="share-input" type='text' value="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}"></input>
        </div> -->
      </div>
    </div>

    <div class="card--container view--text back">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black font--mtgx english">
          <span class="card-name"><b>{{ name }}</b></span>
          <span class="card-type">{{ type_line }}</span>
          {{ oracle_text }}
        </p>
        <!-- <div class="share--card font--mtgx">
          <span class="card-share">Share This Card</span>
          <input class="share-input" type='text' value="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}"></input>
        </div> -->
      </div>
    </div>

  </div>


  <div class="card--button draw-again">
    <a href="{% url 'home:card_new' %}">
    <span class="text--white text--large font--beleren">Draw Another Card</span>
    </a>
  </div>


</div>
{% endblock %}

<!-- <script type="text/javascript" src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/drawacard.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/jquery.flip.min.js' %}"></script>
<script type="text/javascript" src="{% static 'home/js/backgroundTransition.js' %}"></script> -->


<script>
$(".card-share").click(function() {
  console.log("blueberries are wonderful.");
  $(".share-input").toggleClass('active');
});
</script>

home/templates/home/card_new.html
{% extends "home/base.html" %}

{% load static widget_tweaks %}

{% block body_class %}card-new{% endblock %}

{% block content %}

<div class="flexbox">

  <!-- <div class="card--button show-english">
    <span class="text--white text--large">Show Image</span>
  </div> -->

  <div class="card--container view--cover">
    <div class="card--container__wrapper">
      <p class="card--container__text text--white">

        <form method="POST" class="card-form">
          {% csrf_token %}
            <span class="help-text font--mtgx text--white">Language</span>
            {{ form.language | add_class:'custom-form-select' }}<br>
            <span class="help-text font--mtgx text--white">Keyword<br/>
            <span class="help-text-small">(Optional, in English or chosen language)</span></span>
            {{ form.keyword | add_class:'custom-form-field' | attr:"placeholder:"}}<br>
            <button type="submit" class="save btn btn-default text--white text--large font--beleren">Show Text</button>
        </form>

        <br>
      </p>
    </div>
  </div>

  <!-- <div class="card--button draw-again">
    <span class="text--white text--large">Draw again</span>
  </div>
   -->
</div>


{% endblock %}

home/templates/home/index.html
{% extends "home/base.html" %}

{% load static %}

{% block body_class %}index{% endblock %}

{% block content %}
<div class="flexbox">

  <div class="card--container view--cover">
    <div class="card--container__wrapper">
      <p class="card--container__start text--white">
        <a href="{% url 'home:card_new' %}" class="card__text font--beleren">Draw <br>Your Magic<br> Card</a>
      </p>

    </div>
  </div>
</div>

{% endblock %}