draw/urls.py
from django.urls import path

from . import views

app_name = 'draw'
urlpatterns = [
    path('', views.index, name='index'),
    path('card/', views.card_new, name='card_new'),
    # path('card/<int:pk>/', views.card_detail, name='card_detail'),
    path('card/detail/', views.card_detail, name='card_detail'),

]

drawacard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('draw/', include('draw.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

draw/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Card(models.Model):

    LANG_CHOICES = [
        ('ko', 'Korean'),
        ('ja', 'Japanese'),
        ('zhs', 'Chinese'),
    ]

    # card = models.ForeignKey(Card, on_delete=models.CASCADE)
    language = models.CharField(
        max_length=10,
        choices=LANG_CHOICES,
        default='ko',
    )

    keyword = models.CharField(max_length=200,null=True,blank=True)

    drawn_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        # return self.language
        return self.language

    def drawn(self):
        self.drawn_date = timezone.now()
        self.save()

draw/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from .models import Card

from .forms import CardForm
from django.utils import timezone

# for json data
import requests, json, random

def index(request):
    # return HttpResponse("Hello, world. You're at the draw index.")
    all_card = Card.objects.all()
    context = {'all_card': all_card}
    return render(request, 'draw/index.html', context)


def card_new(request):

    if request.method == "POST":
        form = CardForm(request.POST)
        if form.is_valid():
            card = form.save(commit=False)
            card.author = request.user
            card.drawn_date = timezone.now()


            card.save()


            # save the input as chosen_variables
            chosen_language = card.language

            # implement the language variant
            if chosen_language == 'ko':
                language = 'Korean'
            elif chosen_language == 'ja':
                language = 'Japanese'
            else:
                language = 'Chinese'

            # if there is a keyword
            if not card.keyword == None:
                response_string = 'https://api.scryfall.com/cards/search?q=lang%3A'
                response_string += chosen_language

                chosen_keyword = card.keyword
                response_string += '+' + chosen_keyword

                response = requests.get(response_string)
                randomcard = response.json()

                total_cards = int(randomcard["total_cards"])
                random_card_index = random.randint(0,total_cards-1)

                result = randomcard["data"][random_card_index]

            else:
                response_string = 'https://api.scryfall.com/cards/random?q=lang%3A'
                response_string += chosen_language

                response = requests.get(response_string)
                result = response.json()


            try:
                printed_name = result['printed_name']
            except:
                result['printed_name'] = "(Name is empty.)"
            try:
                printed_text = result['printed_text']
            except:
                result['printed_text'] = "(Text is empty.)"
            try:
                oracle_text = result['oracle_text']
            except:
                result['oracle_text'] = "(Text is empty.)"
            try:
                printed_type_line = result['printed_type_line']
            except:
                result['printed_type_line'] = "(Type is empty.)"

            name = result['name']
            printed_name = result['printed_name']

            type_line = result['type_line']
            printed_type_line = result['printed_type_line']

            oracle_text = result['oracle_text']
            printed_text = result['printed_text']

            context = {
                'name': name,
                'printed_name':printed_name,
                'type_line':type_line,
                'printed_type_line':printed_type_line,
                'oracle_text':oracle_text,
                'printed_text':printed_text,
                'language':language
                }

            return render(request, 'draw/card_detail.html', context)
    else:
        form = CardForm()
    return render(request, 'draw/card_new.html', {'form': form})

def card_detail(request):
    return render(request, 'draw/card_detail.html')

draw/templates/draw/base.html
{% load static %}

<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <title>
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'draw/css/style.css' %}">

    </head>

    <body class="{% block body_class %}{% endblock %}">
        <main class="container">

          <img class="background" src="{% static "draw/img/bg_02.jpg" %}" id="bg" alt="background"/>

        {% block content %}
        {% endblock %}

    </body>

    {# Global javascript #}
    <script type="text/javascript" src="{% static 'draw/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'draw/js/jquery.flip.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'draw/js/drawacard.js' %}"></script>

</html>

draw/templates/draw/card_detail.html
{% extends "draw/base.html" %}

{% load static %}

{% block body_class %}card-detail{% endblock %}

{% block content %}
<div class="flexbox">
  <div class="card--button show-english">
    <span class="text--white text--large font--beleren">
      <a href="#" class="show--english">Show in English</a>
      <a href="#" class="show--otherlang hide">Show in {{language}}</a>
    </span>
  </div>

  <div id="card">

    <div class="card--container view--text front">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black korean">
          <span class="card-name"><b>{{ printed_name }}</b></span>
          <span class="card-type">{{ printed_type_line }}</span>
          {{ printed_text }}
        </p>
        <div class="share--card font--mtgx">
          <span class="card-share">Share This Card</span>
          <input class="share-input" type='text' value="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}"></input>
        </div>
      </div>
    </div>

    <div class="card--container view--text back">
      <div class="card--container__wrapper">
        <p class="card--container__text text--black font--mtgx english">
          <span class="card-name"><b>{{ name }}</b></span>
          <span class="card-type">{{ type_line }}</span>
          {{ oracle_text }}
        </p>
        <div class="share--card font--mtgx">
          <span class="card-share">Share This Card</span>
          <input class="share-input" type='text' value="{{ request.build_absolute_uri }}{{ object.get_absolute_url }}"></input>
        </div>
      </div>
    </div>

  </div>

  <div class="card--button draw-again">
    <span class="text--white text--large font--beleren"><a href="{% url 'draw:card_new' %}">Draw Another Card</a></span>
  </div>
</div>
{% endblock %}

<script type="text/javascript" src="{% static 'draw/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'draw/js/drawacard.js' %}"></script>
<script type="text/javascript" src="{% static 'draw/js/jquery.flip.min.js' %}"></script>

<script>
$(".card-share").click(function() {
  console.log("blueberries are wonderful.");
  $(".share-input").toggleClass('active');
});
</script>

draw/templates/draw/card_new.html
{% extends "draw/base.html" %}

{% load static %}

{% block body_class %}card-new{% endblock %}

{% block content %}
<div class="flexbox">

  <!-- <div class="card--button show-english">
    <span class="text--white text--large">Show Image</span>
  </div> -->

  <div class="card--container view--cover">
    <div class="card--container__wrapper">
      <p class="card--container__text text--white">

        <form method="POST" class="card-form">
          {% csrf_token %}

            <span class="help-text text--white">Choose Language</span>
            {{ form.language }}<br>
            <span class="help-text text--white">Optional keyword<br/>
            Keyword either in English or chosen language</span>
            {{ form.keyword }}<br>
            <button type="submit" class="save btn btn-default text--white text--large font--beleren">Show Text</button>
        </form>

        <br>
      </p>
    </div>
  </div>

  <!-- <div class="card--button draw-again">
    <span class="text--white text--large">Draw again</span>
  </div>
   -->
</div>
{% endblock %}

draw/templates/draw/index.html
{% extends "draw/base.html" %}

{% load static %}

{% block body_class %}index{% endblock %}

{% block content %}
<div class="flexbox">

  <div class="card--container view--cover">
    <div class="card--container__wrapper">
      <p class="card--container__start text--white">
        <a href="{% url 'draw:card_new' %}" class="card__text font--beleren">Draw <br>Your Magic<br> Card</a>
      </p>

    </div>
  </div>
</div>

{% endblock %}